version: "3.8"

services: 

  frontend:
    depends_on:
      - backend
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:9897
    volumes:
      - frontend-data:/frontend-app
    ports:
      - "3000:3000"


  backend: 
    depends_on:
      - mysql-container
    build: ./backend
    restart: unless-stopped
    ports:
      - "9897:9897"
    volumes:
      - backend-data:/backend-app
    environment:
      - DB_HOST=mysql-container
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASES}
      
  
  mysql-container:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./postgresql-init:/docker-entrypoint-initdb.d
  

volumes: 
  db:
  backend-data:
  frontend-data: