version: "3.8"

services: 

  backend: 
    depends_on:
      - mysql-container
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "9897:9897"
    volumes:
      - backend-data:/backend-app
    environment:
      - DB_HOST=mysql-container
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=robot_accounts
      - FRONTEND_URL=${FRONTEND_URL}

      
  
  mysql-container:
    image: mysql:8
    container_name: mysql-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=robot_accounts
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d



volumes: 
  db:
  backend-data:
  frontend-data: